name: Feature #템플릿 이름
description: Feature Report # 템플릿 설명(필수)
title: "Feat: " # 이슈나 PR의 제목 템플릿
body:
  - type: markdown
    attributes:
      value: |
        # ⭐️ **구현사항**
        
        * [ ] Task1
        * [ ] Task2
